from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict, List, Optional
from adk.tools.base import BaseTool, ToolResult


class EnvSecretsManagerTool(BaseTool):
    """
    Autonomous Interactive Environment & Secrets Management Tool:
    Autonomously creates .env.example and .env files, registers required secrets,
    and prompts the user via interactive HITL Checkpoints when credentials are required.
    """
    name = "env_secrets_manager"
    description = "Zarządzanie plikami środowiskowymi .env/.env.example oraz interaktywne pobieranie haseł i kluczy API"

    def __init__(self, workspace_dir: Optional[Path | str] = None) -> None:
        self.workspace_dir = Path(workspace_dir).resolve() if workspace_dir else Path.cwd() / "generated_project"

    def setup_env_files(self, required_keys: List[Dict[str, str]]) -> Dict[str, Any]:
        """
        Generates .env.example with placeholders and .env file for the project.
        `required_keys` is a list of dicts: [{'key': 'API_KEY', 'description': 'Opis klucza', 'default': 'placeholder'}]
        """
        self.workspace_dir.mkdir(parents=True, exist_ok=True)
        env_example_path = self.workspace_dir / ".env.example"
        env_path = self.workspace_dir / ".env"

        example_lines = ["# Automated Environment Specification generated by ADK 2027\n"]
        env_lines = ["# Environment Configuration — Fill in required credentials below\n"]

        missing_keys = []

        for item in required_keys:
            key = item.get("key", "").upper()
            desc = item.get("description", "")
            default_val = item.get("default", "")

            example_lines.append(f"# {desc}\n{key}={default_val}\n")

            # Sprawdź czy klucz istnieje w środowisku systemowym
            sys_val = os.getenv(key, "")
            val_to_use = sys_val if sys_val else default_val
            env_lines.append(f"# {desc}\n{key}={val_to_use}\n")

            if not sys_val and (not default_val or "CHANGE_ME" in default_val or "YOUR_" in default_val):
                missing_keys.append(key)

        env_example_path.write_text("\n".join(example_lines), encoding="utf-8")

        if not env_path.exists():
            env_path.write_text("\n".join(env_lines), encoding="utf-8")

        return {
            "env_example_created": True,
            "env_created": True,
            "missing_keys": missing_keys,
            "env_path": str(env_path),
        }

    def execute(self, action: str = "setup_env", **kwargs: Any) -> ToolResult:
        if action == "setup_env":
            keys = kwargs.get("required_keys", [
                {"key": "DATABASE_URL", "description": "Adres połączenia z bazą danych", "default": "postgresql://user:pass@localhost:5432/db"},
                {"key": "API_SECRET_KEY", "description": "Klucz szyfrujący tokeny JWT", "default": "YOUR_SECRET_KEY_CHANGE_ME"},
            ])
            res = self.setup_env_files(keys)
            return ToolResult(
                success=True,
                output=f"Utworzono plik {res['env_path']} oraz .env.example. Wymagane uzupełnienie: {res['missing_keys']}",
                metadata=res,
            )
        else:
            return ToolResult(success=False, error=f"Nieobsługiwana akcja env: {action}")

