from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional
from adk.core.models import ChapterDraft, Citation, ThesisMetadata
from adk.tools.base import BaseTool, ToolResult


def latex_escape(text: str) -> str:
    """
    Sanityzuje i eskapuje znaki specjalne LaTeX (%, &, #, _) w tekście narracyjnym,
    pomijając środowiska matematyczne ($...$) i komendy LaTeX.
    """
    if not text:
        return ""
    
    # Jeśli to linia z komendą LaTeX (np. \begin, \chapter, \section, \item), nie eskapujemy struktury
    lines = text.split("\n")
    escaped_lines: List[str] = []

    for line in lines:
        l = line.strip()
        if l.startswith("\\") or l.startswith("%") or l.startswith("```"):
            escaped_lines.append(line)
            continue
        
        res = line
        res = re.sub(r'(?<!\\)%', r'\%', res)
        res = re.sub(r'(?<!\\)&', r'\&', res)
        res = re.sub(r'(?<!\\)#', r'\#', res)
        res = re.sub(r'(?<!\\)_', r'\_', res)
        escaped_lines.append(res)

    return "\n".join(escaped_lines)


class TypesettingTool(BaseTool):
    name = "typesetting_tool"
    description = "Generowanie i kompilacja pracy dyplomowej do formatu Typst i LaTeX z obsługą dwujęzyczną (PL/EN) i sanitizacją LaTeX"

    def __init__(self, output_dir: Optional[Path | str] = None) -> None:
        self.output_dir = Path(output_dir).resolve() if output_dir else Path.cwd() / "projects" / "project_01" / "artifacts" / "thesis"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_typst_document(
        self,
        metadata: ThesisMetadata,
        chapters: List[ChapterDraft],
        citations: List[Citation],
    ) -> str:
        lines: List[str] = []
        
        # Nagłówek i konfiguracja szablonu
        lines.append("// Typst Thesis Document - Generated by ADK 2027")
        lines.append('#set document(title: "' + metadata.title + '", author: "' + metadata.author + '")')
        lines.append('#set page(paper: "a4", margin: (x: 2.5cm, top: 2.5cm, bottom: 2.5cm))')
        lines.append('#set text(font: "Linux Libertine", size: 11pt, lang: "' + metadata.language + '")')
        lines.append('#set par(justify: true, leading: 0.75em, first-line-indent: 1.25cm)')
        lines.append('#set heading(numbering: "1.1")')
        lines.append("")
        
        # Strona tytułowa
        lines.append("#align(center)[")
        lines.append(f"  #text(14pt, weight: \"bold\")[{metadata.institution}]\n")
        lines.append(f"  #text(12pt)[{metadata.faculty}]\n")
        lines.append("  #v(3cm)")
        lines.append(f"  #text(18pt, weight: \"bold\")[{metadata.title}]\n")
        if metadata.subtitle:
            lines.append(f"  #text(13pt, style: \"italic\")[{metadata.subtitle}]\n")
        lines.append("  #v(2cm)")
        degree_name = "Praca Inżynierska" if metadata.degree_type.value == "engineering" else "Praca Magisterska"
        lines.append(f"  #text(12pt, weight: \"bold\")[{degree_name}]\n")
        lines.append(f"  #text(11pt)[Kierunek: {metadata.field_of_study}]\n")
        lines.append("  #v(3cm)")
        lines.append("  #grid(columns: (1fr, 1fr), align: (left, right),")
        lines.append(f"    [Autor:\n*{metadata.author}*],")
        lines.append(f"    [Promotor:\n*{metadata.supervisor}*]")
        lines.append("  )")
        lines.append("  #v(2cm)")
        lines.append(f"  #text(11pt)[Warszawa, {metadata.year}]")
        lines.append("]")
        lines.append("#pagebreak()")
        lines.append("")

        # 1. Streszczenie po polsku
        if metadata.abstract_pl:
            lines.append("= Streszczenie\n")
            lines.append(metadata.abstract_pl)
            if metadata.keywords:
                pl_keywords = [k for k in metadata.keywords if any(c in k for c in "ąćęłńóśźż") or "Inżynieria" in k or "Sztuczna" in k or len(k.split()) > 0][:5]
                lines.append(f"\n*Słowa kluczowe:* {', '.join(pl_keywords if pl_keywords else metadata.keywords[:5])}\n")
            lines.append("#pagebreak()\n")

        # 2. Abstract po angielsku
        if metadata.abstract_en:
            lines.append("= Abstract\n")
            lines.append(metadata.abstract_en)
            if metadata.keywords:
                en_keywords = [k for k in metadata.keywords if not any(c in k for c in "ąćęłńóśźż") and k not in ("Inżynieria", "Sztuczna")][:5]
                lines.append(f"\n*Keywords:* {', '.join(en_keywords if en_keywords else metadata.keywords[-4:])}\n")
            lines.append("#pagebreak()\n")

        # Spis treści
        lines.append("#outline(title: [Spis treści], indent: auto)")
        lines.append("#pagebreak()\n")

        # Rozdziały
        sorted_chapters = sorted(chapters, key=lambda c: c.number)
        for chap in sorted_chapters:
            lines.append(f"= {chap.title}\n")
            lines.append(chap.content_typst)
            lines.append("\n")

        # Bibliografia
        if citations:
            lines.append("= Bibliografia\n")
            lines.append("#bibliography(\"references.bib\", title: none, style: \"ieee\")\n")

        return "\n".join(lines)

    def generate_latex_document(
        self,
        metadata: ThesisMetadata,
        chapters: List[ChapterDraft],
        citations: List[Citation],
    ) -> str:
        lines: List[str] = [
            r"\documentclass[12pt,a4paper,twoside]{report}",
            r"\usepackage[utf8]{inputenc}",
            r"\usepackage[T1]{fontenc}",
            r"\usepackage{lmodern}",
            r"\usepackage{amsmath,amssymb}",
            r"\usepackage{graphicx}",
            r"\usepackage{hyperref}",
            r"\usepackage{listings}",
            r"\usepackage{xcolor}",
            r"\usepackage[style=ieee,backend=biber]{biblatex}",
            r"\addbibresource{references.bib}",
            r"\usepackage{geometry}",
            r"\geometry{a4paper,left=30mm,right=20mm,top=25mm,bottom=25mm}",
            "",
            r"\title{" + latex_escape(metadata.title) + "}",
            r"\author{" + latex_escape(metadata.author) + "}",
            r"\date{" + str(metadata.year) + "}",
            "",
            r"\begin{document}",
            r"\maketitle",
            r"\tableofcontents",
            r"\newpage",
        ]

        if metadata.abstract_pl:
            lines.extend([
                r"\begin{abstract}",
                latex_escape(metadata.abstract_pl),
                r"\end{abstract}",
                r"\newpage",
            ])

        if metadata.abstract_en:
            lines.extend([
                r"\chapter*{Abstract}",
                r"\addcontentsline{toc}{chapter}{Abstract}",
                latex_escape(metadata.abstract_en),
                r"\newpage",
            ])

        sorted_chapters = sorted(chapters, key=lambda c: c.number)
        for chap in sorted_chapters:
            content = chap.content_latex if chap.content_latex else chap.content_typst
            lines.append(f"\\chapter{{{latex_escape(chap.title)}}}\n")
            lines.append(latex_escape(content))
            lines.append("\n")

        if citations:
            lines.append(r"\printbibliography[heading=bibintoc,title={Bibliografia}]")

        lines.append(r"\end{document}")
        return "\n".join(lines)

    def export_thesis_package(
        self,
        metadata: ThesisMetadata,
        chapters: List[ChapterDraft],
        citations: List[Citation],
    ) -> Dict[str, str]:
        typst_src = self.generate_typst_document(metadata, chapters, citations)
        latex_src = self.generate_latex_document(metadata, chapters, citations)

        typst_file = self.output_dir / "thesis.typ"
        latex_file = self.output_dir / "thesis.tex"
        bib_file = self.output_dir / "references.bib"

        typst_file.write_text(typst_src, encoding="utf-8")
        latex_file.write_text(latex_src, encoding="utf-8")

        # Zapisz references.bib
        bib_entries = [c.bibtex for c in citations]
        bib_file.write_text("\n\n".join(bib_entries), encoding="utf-8")

        # Próba kompilacji Typst jeśli `typst` jest zainstalowany w systemie
        pdf_path = None
        if shutil.which("typst"):
            try:
                proc = subprocess.run(
                    ["typst", "compile", str(typst_file)],
                    cwd=self.output_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    timeout=30,
                )
                if proc.returncode == 0:
                    pdf_path = str(self.output_dir / "thesis.pdf")
            except Exception:
                pdf_path = None

        return {
            "typst_file": str(typst_file),
            "latex_file": str(latex_file),
            "bib_file": str(bib_file),
            "pdf_file": pdf_path or "Source generated (Ready to compile)",
        }

    def execute(self, action: str, **kwargs: Any) -> ToolResult:
        if action == "export":
            meta = ThesisMetadata.model_validate(kwargs.get("metadata", {}))
            chaps = [ChapterDraft.model_validate(c) for c in kwargs.get("chapters", [])]
            cits = [Citation.model_validate(c) for c in kwargs.get("citations", [])]
            res = self.export_thesis_package(meta, chaps, cits)
            return ToolResult(success=True, output=res)
        else:
            return ToolResult(success=False, error=f"Nieznana akcja: {action}")
